Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "lab2-docker"

  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.network "forwarded_port",
    guest: 3000,
    host: 3001,
    auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Lab02-Docker"
    vb.memory = 2048
    vb.cpus = 2
  end
end